name: posgonitor CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build posgonitor
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.18.0'

    - name: Check Go fmt
      run: make gofmt

    - name: Check go mod status
      run: |
        make gomod_tidy
        if [[ ! -z $(git status -s) ]]
        then
          echo "Go mod - state is not clean:"
          git status -s
          git diff "$GITHUB_SHA"
          exit 1
        fi

    - name: Build
      run: make build
