name: 'Build Docker image and publish to Docker Hub'

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Docker hub org and repository name'
        required: false
        default: 'nethermindeth/posmoni'
      tag:
        description: 'Tag for the docker image'
        required: false
        default: ''
      dockerfile:
        description: 'Dockerfile to use'
        required: false
        default: 'Dockerfile'

jobs:
  build-dockers:
    if: github.repository_owner == 'NethermindEth'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up settings
        id: settings
        run: |
          echo ::set-output name=docker_username::${{ secrets.DOCKER_USERNAME }}
          echo ::set-output name=docker_image::${{ github.event.inputs.repo }}
          echo ::set-output name=dockerfile::${{ github.event.inputs.dockerfile }}
          echo ::set-output name=TAG::${{ github.event.inputs.tag }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker Image
        uses: docker/build-push-action@v3
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ${{ steps.settings.outputs.dockerfile }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.settings.outputs.docker_image }}:latest,${{ steps.settings.outputs.docker_image }}:${{ steps.settings.outputs.TAG }}

      - name: Clearing
        if: always()
        run: |
          rm -f ${HOME}/.docker/config.json